platform :ios, '9.3'

use_frameworks!
  
target 'SharePoster_Example' do
  pod 'SharePoster', :path => '../'

  target 'SharePoster_Tests' do
    inherit! :search_paths

    target 'TestShareExtension' do
      pod 'SharePoster', :path => '../'
    
    end
  end
end
